# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://khimo.github.io" # the base hostname & protocol for your site
highlighter: rouge

twitter_username:
github_username:

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true # Auto-generate ID's for headings


# Jekyll collections
collections:
  help_drivers:
    output: true
    permalink: /help_drivers/:path/
  bli_advanced_user_guide:
    output: true
    permalink: /bli-guides/bli_advanced_user_guide/:path
  01-setup-bli-pro:
    output: true
    permalink: /bli-guides/bli-pro-user-guide/01-setup-bli-pro/:path
  bli-pro-user-guide:
    output: true
    permalink: /bli-guides/bli-pro-user-guide/:path
  how-tos:
    output: true
    permalink: /bli-guides/how-tos/:path
  developers-guides:
    output: true
    permalink: /bli-guides/developers-guides/:path
  lua-macro-snippets:
    output: true
    permalink: /bli-guides/how-tos/howto-lua-macros/:path
    directory: /bli-guides/_lua-macro-snippets/

  
collections_dir: bli-guides

#jekyll plugins for TOC and sitemap
plugins:
  - jekyll-toc
  - jekyll-sitemap
