# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://khimo.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

# Jekyll collections
collections:
  help_drivers:
    output: true
    permalink: /help_drivers/:path/
  bli_advanced_user_guide:
    output: true
    permalink: /bli-guides/bli_advanced_user_guide/:path
  bli-pro-user-guide:
    output: true
    permalink: /bli-guides/bli-pro-user-guide/:path
  bli-pro-user-guide/setup-bli-pro:
    output: true
    permalink: /bli-guides/bli-pro-user-guide/setup-bli-pro/:path
  
collections_dir: bli-guides

#jekyll plugins for TOC and sitemap
plugins:
  - jekyll-toc
  - jekyll-sitemap
